### ISSUE TITLE
What is the meaning of [3]?

### ISSUE THREAD

**Issue by qiaojy19** [mattbev/6.867-final-project#4]
I don't know what's the meaning of [3], in the section "Setting up the federated learning enviroment and basic attacks". Does it mean the paper "Deep Models Under the GAN: Information Leakage from Collaborative Deep Learning"?

> I think we should first set up a model of federated learning (using the MNIST dataset), where malicious users only train a GAN to reconstruct other participants private data as in [3]. 

Thank you!

**Comment by mattbev** [comment]
This is a relic of our internal planning for the project and refers to a citation in our strategy document. I will be cleaning up the repo today and will update the README. I'll close this issue when completed!

**Comment by mattbev** [comment]
refactor is done! I've deleted all branches but the main branch and added some next steps in the "future work" section of the README if you would like to contribute to the project
