### ISSUE TITLE
Error: Input type and weight type should be the same

### ISSUE THREAD

**Issue by qiaojy19** [mattbev/6.867-final-project#7]
Hi, I just git clone this project and run `python baseline.py basic`, it reports the Error:
> RuntimeError: Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same

Then I configure some variable in uap attack to cuda with `.cuda()`, there is another error:

> File "/home/tianjc/project/mit_attack/utils/models.py", line 94, in forward
> orig_img = x * self.std_tensor + self.mean_tensor # Put image into original form
> RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

I have a solution is that I can directly set device = 'cpu', but I still wish to train uap attack with gpu. Could you help me? Thank you very much.

**Comment by qiaojy19** [comment]
> Hi, I just git clone this project and run `python baseline.py basic`, it reports the Error:
> 
> > RuntimeError: Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same
> 
> Then I configure some variable in uap attack to cuda with `.cuda()`, there is another error:
> 
> > File "/home/tianjc/project/mit_attack/utils/models.py", line 94, in forward
> > orig_img = x * self.std_tensor + self.mean_tensor # Put image into original form
> > RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
> 
> I have a solution is that I can directly set device = 'cpu', but I still wish to train uap attack with gpu. Could you help me? Thank you very much.

I modify the UAP(device) and some other code to set use_cuda=True, and the program runs successfully. I have no problems. Thanks.

**Comment by mattbev** [comment]
Thanks for pointing this out. There are undoubtedly areas in this repo that could use improvement, so if you want to submit your solution as a pull request I can merge it in
