### ISSUE TITLE
should be the same or input should be a MKLDNN tensor and weight is a dense tensor

### ISSUE THREAD

**Issue by AriesQa** [mattbev/6.867-final-project#8]
Hi, 

Thanks for sharing the code. Please help me to solve this issue.  I ran python baseline.py federated

![Screenshot (87)](https://user-images.githubusercontent.com/85681572/160228595-56d3da99-0b69-4339-9daa-938dfc697c6a.png)

**Comment by mattbev** [comment]
Hi @AriesQa, I have identified the issue -- the training process for the UAP attack does not elegantly handle loading tensors to GPU (currently hardcoded). After looking through the code, I notice there are also a few other areas that could use an update. I will push some fixes and tag you when they are complete.

**Comment by mattbev** [comment]
For a quick fix, see here: https://github.com/mattbev/6.867-final-project/issues/7

**Comment by AriesQa** [comment]
Ok. Thank you
